// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: processor.proto

#include "processor.pb.h"
#include "processor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace distributed {

static const char* Processor_method_names[] = {
  "/distributed.Processor/Process",
};

std::unique_ptr< Processor::Stub> Processor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Processor::Stub> stub(new Processor::Stub(channel, options));
  return stub;
}

Processor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Process_(Processor_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Processor::Stub::Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::distributed::ProcessReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::distributed::ProcessRequest, ::distributed::ProcessReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Process_, context, request, response);
}

void Processor::Stub::async::Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::distributed::ProcessRequest, ::distributed::ProcessReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Process_, context, request, response, std::move(f));
}

void Processor::Stub::async::Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Process_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>* Processor::Stub::PrepareAsyncProcessRaw(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::distributed::ProcessReply, ::distributed::ProcessRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Process_, context, request);
}

::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>* Processor::Stub::AsyncProcessRaw(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncProcessRaw(context, request, cq);
  result->StartCall();
  return result;
}

Processor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Processor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Processor::Service, ::distributed::ProcessRequest, ::distributed::ProcessReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Processor::Service* service,
             ::grpc::ServerContext* ctx,
             const ::distributed::ProcessRequest* req,
             ::distributed::ProcessReply* resp) {
               return service->Process(ctx, req, resp);
             }, this)));
}

Processor::Service::~Service() {
}

::grpc::Status Processor::Service::Process(::grpc::ServerContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace distributed

