// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: processor.proto
#ifndef GRPC_processor_2eproto__INCLUDED
#define GRPC_processor_2eproto__INCLUDED

#include "processor.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace distributed {

class Processor final {
 public:
  static constexpr char const* service_full_name() {
    return "distributed.Processor";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::distributed::ProcessReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::distributed::ProcessReply>> AsyncProcess(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::distributed::ProcessReply>>(AsyncProcessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::distributed::ProcessReply>> PrepareAsyncProcess(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::distributed::ProcessReply>>(PrepareAsyncProcessRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::distributed::ProcessReply>* AsyncProcessRaw(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::distributed::ProcessReply>* PrepareAsyncProcessRaw(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::distributed::ProcessReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>> AsyncProcess(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>>(AsyncProcessRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>> PrepareAsyncProcess(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>>(PrepareAsyncProcessRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response, std::function<void(::grpc::Status)>) override;
      void Process(::grpc::ClientContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>* AsyncProcessRaw(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::distributed::ProcessReply>* PrepareAsyncProcessRaw(::grpc::ClientContext* context, const ::distributed::ProcessRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Process_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Process(::grpc::ServerContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Process() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcess(::grpc::ServerContext* context, ::distributed::ProcessRequest* request, ::grpc::ServerAsyncResponseWriter< ::distributed::ProcessReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Process<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Process() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::distributed::ProcessRequest, ::distributed::ProcessReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::distributed::ProcessRequest* request, ::distributed::ProcessReply* response) { return this->Process(context, request, response); }));}
    void SetMessageAllocatorFor_Process(
        ::grpc::MessageAllocator< ::distributed::ProcessRequest, ::distributed::ProcessReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::distributed::ProcessRequest, ::distributed::ProcessReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Process(
      ::grpc::CallbackServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Process<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Process() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Process() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestProcess(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Process() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Process(context, request, response); }));
    }
    ~WithRawCallbackMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Process(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Process : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Process() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::distributed::ProcessRequest, ::distributed::ProcessReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::distributed::ProcessRequest, ::distributed::ProcessReply>* streamer) {
                       return this->StreamedProcess(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Process() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Process(::grpc::ServerContext* /*context*/, const ::distributed::ProcessRequest* /*request*/, ::distributed::ProcessReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedProcess(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::distributed::ProcessRequest,::distributed::ProcessReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Process<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Process<Service > StreamedService;
};

}  // namespace distributed


#endif  // GRPC_processor_2eproto__INCLUDED
