<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processor.proto

namespace GPBMetadata;

class Processor
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¶
processor.protodistributed"
ProcessRequest
text (	"
ProcessReply
result (	2N
	ProcessorA
Process.distributed.ProcessRequest.distributed.ProcessReplybproto3'
        , true);

        static::$is_initialized = true;
    }
}

